### ISSUE TITLE
Fix order of rules to execute

### ISSUE THREAD

**Issue by ljrk0** [rchurchley/beamercolortheme-owl#1]
I think in Makefiles the order of rules / dependencies matters -- at least it seems for me to be the case.
Just running `make sty` doesn't work for me, I need to do this:

```
-$(PACKAGE_STY): $(PACKAGE_SRC) $(INS) | $(CACHE_DIR) clean-cache
+$(PACKAGE_STY): $(PACKAGE_SRC) $(INS) | clean-cache $(CACHE_DIR)
```

... in order to build correctly, otherwise it cannot write as the directory doesn't exist.

**Comment by rchurchley** [comment]
You're absolutely right. Thanks for the fix!
